### ISSUE TITLE
Request for small enhancement - disconnect command

### ISSUE THREAD

**Issue by grymoire** [DangerousPrototypes/BusPirate5-firmware#123] opened 2024-10-08 18:59 UTC
This is a minor convenience.

When you are connected to the BP and you want to disconnect so you can copy a file onto the BP, the only way to do this is to (1) use your terminal program to disconnect, (2) unplug the BP, or (3) type "#" to reset the BP.

Disadvantages of Option  (1 ) - the file system remains read only. If you want to copy a file onto the BP, you have to use option 1 or 3.

Disadvantages of (2) - you have to take your hands off the keyboard.  Replugging a USB cable sometimes causes fumbling, and takes time, and if you do this several times a day this is awkward.

Disadvantages of (3) This works, but my Linux system takes a few seconds to unmount and remount the file system, and the BusPirate is reset. In  addition, my Linux system makes an alert sound when the FS disconnects and another when it remounts. _Be-Bloop......... Boop-Bleep._ This can get irritating the ears if heard multiple times an hour.

A command that would (a) terminate the serial connection, and (b) have the file system remounted read/write would be more convenient.

**Comment by henrygab** [comment] 2024-10-10 21:53
This is a duplicate of (a small part of) #110.

The current mechanism used for storage is only 97.2% safe(+).  Soon, it will not be possible to write from the host by default, unless explicitly the BP5 is switched into a `host-exclusive` mode.  There will be a command to switch the BP5 to that mode, and possibly also a boot method (e.g., holding the button while plugging in) will also go to that mode.

<hr/><details><summary>(+)</summary><p/>

85.4% of people believe a percentage statistic when it has a decimal point.  ;-)

</details>

**Closed by henrygab** 2024-10-10 21:53 UTC
Labels: duplicate
